//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonMoudle.MailHunter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailHunter.SendNowSoap")]
    public interface SendNowSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  project_category_code 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendToOne", ReplyAction="*")]
        CommonMoudle.MailHunter.SendToOneResponse SendToOne(CommonMoudle.MailHunter.SendToOneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToOne", Namespace="http://tempuri.org/", Order=0)]
        public CommonMoudle.MailHunter.SendToOneRequestBody Body;
        
        public SendToOneRequest() {
        }
        
        public SendToOneRequest(CommonMoudle.MailHunter.SendToOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendToOneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string content;
        
        public SendToOneRequestBody() {
        }
        
        public SendToOneRequestBody(string project_category_code, string toname, string toemail, string fromname, string fromemail, string subject, string content) {
            this.project_category_code = project_category_code;
            this.toname = toname;
            this.toemail = toemail;
            this.fromname = fromname;
            this.fromemail = fromemail;
            this.subject = subject;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToOneResponse", Namespace="http://tempuri.org/", Order=0)]
        public CommonMoudle.MailHunter.SendToOneResponseBody Body;
        
        public SendToOneResponse() {
        }
        
        public SendToOneResponse(CommonMoudle.MailHunter.SendToOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendToOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendToOneResult;
        
        public SendToOneResponseBody() {
        }
        
        public SendToOneResponseBody(bool SendToOneResult) {
            this.SendToOneResult = SendToOneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendNowSoapChannel : CommonMoudle.MailHunter.SendNowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendNowSoapClient : System.ServiceModel.ClientBase<CommonMoudle.MailHunter.SendNowSoap>, CommonMoudle.MailHunter.SendNowSoap {
        
        public SendNowSoapClient() {
        }
        
        public SendNowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendNowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendNowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendNowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CommonMoudle.MailHunter.SendToOneResponse CommonMoudle.MailHunter.SendNowSoap.SendToOne(CommonMoudle.MailHunter.SendToOneRequest request) {
            return base.Channel.SendToOne(request);
        }
        
        public bool SendToOne(string project_category_code, string toname, string toemail, string fromname, string fromemail, string subject, string content) {
            CommonMoudle.MailHunter.SendToOneRequest inValue = new CommonMoudle.MailHunter.SendToOneRequest();
            inValue.Body = new CommonMoudle.MailHunter.SendToOneRequestBody();
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.toname = toname;
            inValue.Body.toemail = toemail;
            inValue.Body.fromname = fromname;
            inValue.Body.fromemail = fromemail;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            CommonMoudle.MailHunter.SendToOneResponse retVal = ((CommonMoudle.MailHunter.SendNowSoap)(this)).SendToOne(inValue);
            return retVal.Body.SendToOneResult;
        }
    }
}
